### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by thangld322** [wordijp/golang-re2#1]
Hi,
I do a benchmark test with your library and got this error.
My code:
```
// re2
func match_re2(data string, pattern string, loop int) {
	r, _ := re2.MustCompile(pattern)
	//defer closer.Close(r)
	for i := 1;  i<= loop; i++ {
		r.FindAllStringIndex(data, -1)
		//r.FindStringSubmatch(data)
	}
}

func measure_re2(data string, pattern string, loop int) {
	start := time.Now()
	match_re2(data, pattern, loop)
	elapsed := time.Since(start)
	fmt.Printf("%f\n", float64(elapsed) / float64(time.Millisecond))
}

func main() {
        data := "test@test.com http://test.com/test 127.0.0.1"
	loop := 1000000
        // re2
	measure_re2(data, `[\w\.+-]+@[\w\.-]+\.[\w\.-]+`, loop)
}
```

Error:
```
panic: runtime error: cgo argument has Go pointer to Go pointer
goroutine 1 [running]:
github.com/wordijp/golang-re2.(*Regexp).FindAllIndex.func1(0xc000062080, 0xc000012010, 0xc000012020, 0xc00004ce20)
	/home/thangld/go/src/github.com/wordijp/golang-re2/re2.go:357 +0xce
github.com/wordijp/golang-re2.(*Regexp).FindAllIndex(0xc000062080, 0xc0001e9f40, 0x3c, 0x40, 0xffffffffffffffff, 0x40, 0x48b616, 0x5e3d15f6)
	/home/thangld/go/src/github.com/wordijp/golang-re2/re2.go:357 +0x149
github.com/wordijp/golang-re2.(*Regexp).FindAllStringIndex(...)
	/home/thangld/go/src/github.com/wordijp/golang-re2/re2.go:411
main.match_re2(0x53c0b1, 0x3c, 0x538222, 0x1c, 0xf4240)
	/home/thangld/Gitlab/grok/example/main.go:54 +0xa6
main.measure_re2(0x53c0b1, 0x3c, 0x538222, 0x1c, 0xf4240)
	/home/thangld/Gitlab/grok/example/main.go:61 +0x8b
main.main()
	/home/thangld/Gitlab/grok/example/main.go:121 +0x1a2
```

**Comment by lisp-the-great** [comment]
Same here([re2.go#L357](https://github.com/wordijp/golang-re2/blob/master/re2.go#L357)). I think it is the 2nd parameter `&cre_input` that causes this panic.

And here is my solution: (update on [re2.go#L336](https://github.com/wordijp/golang-re2/blob/master/re2.go#L336))
```go
c_input := C.malloc(C.size_t(len(b)))
defer C.free(c_input)
C.memcpy(c_input, unsafe.Pointer(&b[0]), C.size_t(len(b)))
// ...
cre2_input.data = (*C.char)(c_input)
```

reference to [cgo doc](https://golang.org/cmd/cgo/#hdr-Passing_pointers).
